FROM node:20-bullseye

WORKDIR /app

COPY . .

RUN npm install --no-audit --no-fund

# Generate Prisma client
RUN npx prisma generate || true

EXPOSE 4000

CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/server.ts"]